# Generated by Django 3.2.9 on 2021-11-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.BigIntegerField(default='null', unique=True, verbose_name='Id usuario')),
                ('producto', models.IntegerField(default='null', unique=True, verbose_name='Código Producto')),
                ('factura_fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('direccion_envio', models.CharField(default='null', max_length=80, verbose_name='Direccion de envío')),
                ('metodo_pago', models.CharField(default='null', max_length=20, verbose_name='Método de pago')),
                ('valor_envio', models.IntegerField(default='null', verbose_name='Balor de envío')),
                ('valor_producto', models.IntegerField(default='null', verbose_name='Valor de producto')),
                ('valor_impuesto', models.IntegerField(default='null', verbose_name='Valor de impuesto')),
                ('subtotal', models.IntegerField(default='null', verbose_name='Subtotal')),
                ('valor_total', models.IntegerField(default='null', verbose_name='Valor total')),
            ],
        ),
    ]
